<a href="https://colab.research.google.com/github/B-bori/Codes-of-AI-BASICS-Lecture/blob/master/20200320.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
d = [1.0, 0.0] --> list [not vector]

In [0]:
print(d)

[1.0, 0.0]


In [0]:
l=[0.0, 1.0] --> list [not a vector]

In [0]:
h=[1.0,2.0,3.0] --> list [not a vector]
print(h)

[1.0, 2.0, 3.0]


In [0]:
d+l+h

[1.0, 0.0, 0.0, 1.0, 1.0, 2.0, 3.0]

In [0]:
print(d+l)

[1.0, 0.0, 0.0, 1.0]


In [0]:
from numpy import array  
import numpy as np

In [0]:
d=[1.0, 0.0] --> list(not a vector)
l=[0.0, 1.0] --> list(not a vector)
k=[1.0, 2.0] --> list(not a vector)

In [0]:
from numpy import array
M=array[[1,2],[3,4]]
print(M)

TypeError: ignored

In [0]:
d+l+k

[1.0, 0.0, 0.0, 1.0, 1.0, 2.0]

In [0]:
array(d) --> now list d is converted into array (vector or matrix)

array([1., 0.])

In [0]:
array(1)
array(k)

array([1., 2.])

In [0]:
array(l)

array([0., 1.])

In [0]:
array(k)

array([1., 2.])

In [0]:
array(d) + array(l)

array([1., 1.])

In [0]:
d=[1.0, 0.0]
l=[0.0, 1.0]
k=[1.0, 2.0]
d+l+k

[1.0, 0.0, 0.0, 1.0, 1.0, 2.0]

In [0]:
d1=array(d) #d1 is the real vector to handle by yourself, d is forever list, not a vector, but array(d) means it converts d into vector, but not stores in the computer
l1=array(l) #l is a list, array (l) means to return l to vector, but it doesn't have any memory, so disappear, however, l1 stores the returned value of array function, so l1 is forever a proper vector
k1=array(k)
d1+l1+k1 

array([2., 3.])

In [0]:
h=[1.0, 2.0, 3.0]
h1=array(h)
d1+h1

ValueError: ignored

In [0]:
d1 * l1 # dot product - Linear Algebra term.
        # expected result= (d1,1*l1,1)+(d1,2*l1,2) --> vector (matrix) dot product

array([0., 0.])

In [0]:
l1*k1

array([0., 2.])

In [0]:
d2=array([1,2,3])
d3=array([3,4,5])
d2+d3

array([4, 6, 8])

In [0]:
d2*d3

array([ 3,  8, 15])

In [0]:
d2/d3

array([0.33333333, 0.5       , 0.6       ])

In [0]:
d2-d3

array([-2, -2, -2])

In [0]:
matrixA=[[2.0,3.0],[3.0,4.0]]

In [0]:
print(matrixA)

[[2.0, 3.0], [3.0, 4.0]]


In [0]:
matrixB=[[-2.0,-3.0], [-3.0, -4.0]]
print(matrixB)

[[-2.0, -3.0], [-3.0, -4.0]]


In [0]:
matrixA+matrixB

[[2.0, 3.0], [3.0, 4.0], [-2.0, -3.0], [-3.0, -4.0]]

In [0]:
matrixA1=array(matrixA)
matrixB1=array(matrixB)

In [0]:
matrixA1+matrixB1

array([[0., 0.],
       [0., 0.]])

In [0]:
matrixA1*matrixB1

array([[ -4.,  -9.],
       [ -9., -16.]])

In [0]:
matrixX=[[2.0,3.0,4.0],[3.0,4.0,5.0],[4.0,5.0,6.0]] 
matrixY=[[-2.0,-3.0,-4.0],[-3.0,-4.0,-5.0],[-4.0,-5.0,-6.0]]
matrixX1=array(matrixX)
matrixY1=array(matrixY)

In [0]:
matrixX1[1,1]*matrixY1[1,2] #(1,1) in matrixX * (1,2) in matrixY
                            # -6 assumed, but -20 turns up!!!
                            #(reason: computer starts with 0, but LA term starts with 1)

-20.0

In [0]:
matrixX1[0,0]*matrixY1[0,1]

-6.0

In [0]:
from numpy import vstack #stacking the arrays (or row vectors) in a vertical way

In [0]:
a1=array([1,2,3]) # a row vector (1,2,3)

In [0]:
a2=array([2,3,4]) # a row vector (2,3,4)

In [0]:
# I want to make 2 by 3 matrix with the two row vectors a1, and a2

In [0]:
a3=vstack((a1,a2))

In [0]:
print(a3)

[[1 2 3]
 [2 3 4]]


In [0]:
a4=vstack((a2,a1))

In [0]:
print(a4)

[[2 3 4]
 [1 2 3]]


In [0]:
a1list=[1,2,3]
a2list=[2,3,4]
a1list+a2list

[1, 2, 3, 2, 3, 4]

In [0]:
a1+a2

array([3, 5, 7])

In [0]:
from numpy import hstack #stacking the arrays (or column vectors) in a horizontal way
a5=hstack((a1,a2))

In [0]:
print(a5)

[1 2 3 2 3 4]


In [0]:
a1*a2

array([ 2,  6, 12])

In [0]:
scalar= a1[0]*a2[0]+a1[1]*a2[1]+a1[2]*a2[2] #exercise dot product (stupid way)

In [0]:
print(scalar)

20


In [0]:
dotproduct_scalar=a1.dot(a2) #exercise dot product (better way)// Python's dot product function (imported from Numpy) is being used, which is really powerful
print(dotproduct_scalar)

20


In [0]:
dotproduct2_scalar=a2.dot(a2)
print(dotproduct2_scalar) 

29


In [0]:
dotproduct3_scalar=a1.dot(a1)
print(dotproduct3_scalar) 

14


In [0]:
dotproduct4_scalar=a2.dot(a1)
print(dotproduct4_scalar) 

20


In [0]:
dotproduct4_scalar=np.dot(a1,a2)
print(dotproduct4_scalar) 

NameError: ignored