<a href="https://colab.research.google.com/github/B-bori/Codes-of-AI-BASICS-Lecture/blob/master/%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%ED%95%99.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# invert matrix
from numpy import array
from numpy.linalg import inv #define matrix
A=array([
[1.0, 2.0],
[3.0, 4.0]
])
print(A)
#invert matrix
B=inv(A)
#multiply A and B
I=A.dot(B)
print(I)

In [0]:
# LU decomposition
from numpy import array
from scipy.linalg import lu
# define a square matrix
A=array([[1,2,3],
[4,5,6],
[7,8,9]])
print(A)
# factorize
P,L,U= lu(A)
print(P)
print(L)
print(U)
#reconstruct
B=P.dot(L).dot(U)
print(B)

In [0]:
# eigendecomposition example with Python
from numpy import array
from numpy.linalg import eig # define matrix
A=array([[2,2],[16,6]])
print(A)
#factorize
values, vectors=eig(A)
print(values)
print(vectors)

[[ 2  2]
 [16  6]]
[-2. 10.]
[[-0.4472136  -0.24253563]
 [ 0.89442719 -0.9701425 ]]


In [0]:
# SVD decomposition
 from numpy import array
 from numpy import dot
 from numpy import transpose
from scipy.linalg import svd #define a matrix
A=array([
[5,4,1],
[5,5,0],
[0,0,5],
[1,0,4]])
print(A)
#factorize
U,s,V= svd(A)
print(U)
print(s)
print(V)
B= U.dot(s).dot(V) # is that right one? # is this your one of the assignments.
print(B) # should be A=B?

[[5 4 1]
 [5 5 0]
 [0 0 5]
 [1 0 4]]
[[-0.67096878  0.02362898 -0.46466034 -0.57735027]
 [-0.7197425   0.20541998  0.47585716  0.46188022]
 [-0.09389374 -0.77048084  0.52682373 -0.34641016]
 [-0.15151103 -0.6029955  -0.52925183  0.57735027]]
[9.6438109  6.36389089 0.70555232]
[[-0.73674894 -0.65146317 -0.1810987 ]
 [ 0.0852072   0.17624687 -0.9806512 ]
 [-0.67077622  0.73792464  0.07434034]]
[[ 1.00000000e+00  6.22904435e-17 -2.01743020e-16]
 [ 6.22904435e-17  1.00000000e+00  1.68695960e-17]
 [-2.01743020e-16  1.68695960e-17  1.00000000e+00]]
